version: "3"
services:
  php:
    build:
      context: php/php74
    volumes:
      - ../:/docker
      #- ./php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    expose:
      - 9501
    networks:
      web:
  nginx:
    image: nginx:1.22.0
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx:rw
    ports:
      - "80:80"
    restart: always
    networks:
      web:
networks:
  web:
